displayName: Deployment Strategy
type: middleware
iconPath: .assets/icon.png

import: git.uxxi.net/projects/PIL/repos/uxxi_devops_deployment-strategy

summary: 'Request header for deployment strategy'

testData:
  Headers:
    X-Demo: '{ "blue": "valor1",  "green": "valor2" }'
    X-URL: '{{URL}}'
