apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-plugins-pvc
  namespace: traefik
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi